version: "3.9"

services:
  web:
    container_name: website
    build:
      context: ./web
      target: app
    ports:
      - "8000:8000" # Right-hand port must match the Dockerfile
    depends_on:
      - api
      - db
    links:
      - api
    stop_signal: SIGINT
  api:
    container_name: users-api
    restart: always
    build:
      context: ./api
      target: app
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
    command: /start-reload.sh
    environment:
      VARIABLE_NAME: api
  db:
    container_name: users-db
    image: redis/redis-stack:6.2.2-v5
    restart: always
    ports:
      - "6379:6379" # Server
      - "8001:8001" # RedisInsight
    command: redis-server --loglevel warning
    volumes:
      - $PWD/redis:/data
      - $PWD/data/redisinsight:/redisinsight