version: "3.9"

services:
  web:
    build:
      context: ./web
      target: app
    ports:
      - "8000:8000" # Right-hand port must match the Dockerfile
    depends_on:
      - api
      - db
    links:
      - api
      - db
    stop_signal: SIGINT
    volumes:
      # Pick up code changes while running
      # Right-hand directory must match the target WORKDIR in Dockerfile
      - ./web/src/web:/app
    env_file:
      - web/secrets.env
    environment:
      REDIS_OM_URL: redis://db:6379
  api:
    restart: always
    build:
      context: ./api
      target: app
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
    command: /start-reload.sh
    volumes:
      # Pick up code changes while running
      # Right-hand directory must match the target WORKDIR in Dockerfile
      - ./api/src/api:/app
    environment:
      VARIABLE_NAME: api
      REDIS_OM_URL: redis://db:6379
  db:
    image: redis/redis-stack:6.2.2-v5
    restart: always
    ports:
      - "6379:6379" # Server
      - "8001:8001" # RedisInsight
    environment:
      REDIS_ARGS: --save 20 1
    volumes:
      - ./redis:/data
      - ./redisinsight:/redisinsight