version: "3.9"

services:
  web:
    container_name: xmail-web
    build:
      context: .
      target: app
    ports:
      - "8000:8000" # Right-hand port must match the Dockerfile
    depends_on:
      - db
    links:
      - db
    stop_signal: SIGINT
    volumes:
      # Pick up code changes while running
      # Right-hand directory must match the target WORKDIR in Dockerfile
      - ./src/xmail:/app
    env_file: ./secrets.env
    environment:
      REDIS_OM_URL: redis://db:6379
  db:
    container_name: xmail-db
    image: redis/redis-stack:6.2.2-v5
    restart: always
    ports:
      - "6379:6379" # Server
      - "8001:8001" # RedisInsight
    environment:
      REDIS_ARGS: --save 20 1
    volumes:
      - ./redis:/data
      - ./redisinsight:/redisinsight